config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "users#index"
  resources :users
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries

  mount_uploader :image, ImageUploader
  
  validates :nickname, presence: true

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank? 
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
    resource.image.attach(account_update_params[:image])
  end

  def after_update_path_for(resource)
    user_path(@user.id)
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)

    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:image, :image_cache, :email, :password, :password_confirmation, :nickname, :comment, :content, :twitter, :instagram).merge(id: current_user.id)
  end

  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<%= render "shared/header" %>

<div class='main'>

  <div class='call-contents'>
    <h2 class='call-title'>
      気軽に相談してみよう！
    </h2>
  </div>

  <div class='user-lists'>
    <div class='login-user'>
      <h2 class='login-user-title'>
        ログイン中ユーザー
      </h2>
      <div class='user-list'>
        <% @users.each do |user| %>
          <div class='user-wrapper'>
            <%= link_to user_path(user.id) do %>
              <%= image_tag user.image.thumb50.url, class:"user_image" %>
              <div class='user-body'>
                <div class='header_comment'>
                  <%= user.comment %>
                </div>
                <div class='user_name'>
                  <%= user.nickname %>
                </div>
                <p class='rating-star'>
                  <%= image_tag "star-on.png" %>
                </p>
                <div class='tag-list'>
                  <p>仕事 なんでも</p>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class='high-rate-user'>
      <h2 class='high-rate-user-title'>
        評価の高いユーザー
      </h2>
      <div class='user-wrapper'>
        <%#= link_to image_tag(.image, class: :user_image) %>
        <div class='user-body'>
          <%#= link_to class: :header-comment %>
          <%#= link_to class: :user-name %>
          <p class='rating-star'>
            <%#= %>
          </p>
          <div class='tag-list'>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class='user-show'>
  <div class='chat-start'>
    <div class='chat-start-btn'>
      <% unless current_user.id == @user.id %>
        <% if @isRoom == true %>
          <%= link_to "メッセージを送る", room_path, class:"chat-start-red-btn" %>
        <% else %>
          <%= form_with model: @room, lpcal: true do |f| %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :user_id, value: @user.id %>
            <% end %>
            <%= f.submit "メッセージを送る", class:"chat-start-red-btn" %>
         <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class='user-profile'>
    <%= image_tag @user.image.thumb.url, class:"user_image" %>
    <p class='user-name'>
    <%= @user.nickname %>
    </p>
    <p class='profile-comment'>
    <%= @user.content %>
    </p>
    <div class='sns-link'>
      <ul class="snsbtniti">
        <li><a href="TwitterのプロフィールURL" class="flowbtn6 fl_tw1"><i class="fab fa-twitter"></i></a></li>
        <li><a href="インスタのプロフィールURL" class="flowbtn6 insta_btn6"><i class="fab fa-instagram"></i></a></li>
      </ul>
    </div>
    <div class='tag-list'>
    </div>
    <div class='rating-star'>
    </div>
    <%= link_to "プロフィールの編集", edit_user_registration_path(@user.id), method: :get, class: "user-edit-btn" %>
    <p class="or-text">or</p>
    <%= link_to "削除", user_registration_path(@user.id), method: :delete, class:"user-destroy" %>
  </div>
</div>